#!/usr/bin/env bash

set -ex

git fetch origin
npm run build
touch build/.nojekyll
cd build
git init
git checkout -b gh-pages
git add --all --force
git commit -m "Deployment"
git remote add proj ..
git push --force proj gh-pages
rm -rf .git
cd ..
git branch --force gh-pages_bak origin/gh-pages || true
git push --force origin gh-pages
