#!/usr/bin/env bash

set -ex

git fetch origin
npm run build
touch build/.nojekyll
cd build
git init
git checkout -b gh_pages
git add --all --force
git commit -m "Deployment"
git remote add proj ..
git push --force proj gh_pages
rm -rf .git
cd ..
git branch --force gh_pages_bak origin/gh_pages || true
git push --force origin gh_pages
